services:
  # Backend API Service
  - type: web
    name: fakedetector-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_api_server.py
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
      - key: ALLOWED_ORIGINS
        value: "*"  # Allow all origins initially, we'll update this later

  # Frontend Next.js Service
  - type: web
    name: fakedetector-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: fakedetector-api
          type: web
          property: host  # Using host instead of url
